#!/bin/zsh

python indeed_job_salary.py -l state -j "Business Analyst"
python indeed_job_salary.py -l state -j "Marketing Manager"
python indeed_job_salary.py -l state -j "Product Manager"
python indeed_job_salary.py -l state -j "Software Engineer"
python indeed_job_salary.py -l state -j "Marketing Specialist"
python indeed_job_salary.py -l state -j "Data Scientist"
python indeed_job_salary.py -l state -j "Data Analyst"
python indeed_job_salary.py -l state -j "Business Intelligence Analyst"
python indeed_job_salary.py -l state -j "Financial Analyst"
python indeed_job_salary.py -l state -j "Data Engineer"

python indeed_job_salary.py -l city -j "Business Analyst"
python indeed_job_salary.py -l city -j "Marketing Manager"
python indeed_job_salary.py -l city -j "Product Manager"
python indeed_job_salary.py -l city -j "Software Engineer"
python indeed_job_salary.py -l city -j "Marketing Specialist"
python indeed_job_salary.py -l city -j "Data Scientist"
python indeed_job_salary.py -l city -j "Data Analyst"
python indeed_job_salary.py -l city -j "Business Intelligence Analyst"
python indeed_job_salary.py -l city -j "Financial Analyst"
python indeed_job_salary.py -l city -j "Data Engineer"
